#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7FD9FCCB000BEEEE (meyering@fb.com)
#
Name     : diffutils
Version  : 3.6
Release  : 20
URL      : http://ftp.gnu.org/gnu/diffutils/diffutils-3.6.tar.xz
Source0  : http://ftp.gnu.org/gnu/diffutils/diffutils-3.6.tar.xz
Source99 : http://ftp.gnu.org/gnu/diffutils/diffutils-3.6.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: diffutils-bin
Requires: diffutils-doc
Requires: diffutils-locales

%description
This directory contains the GNU diff, diff3, sdiff, and cmp utilities.
Their features are a superset of the Unix features and they are
significantly faster.

%package bin
Summary: bin components for the diffutils package.
Group: Binaries

%description bin
bin components for the diffutils package.


%package doc
Summary: doc components for the diffutils package.
Group: Documentation

%description doc
doc components for the diffutils package.


%package locales
Summary: locales components for the diffutils package.
Group: Default

%description locales
locales components for the diffutils package.


%prep
%setup -q -n diffutils-3.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1495461038
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1495461038
rm -rf %{buildroot}
%make_install
%find_lang diffutils

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cmp
/usr/bin/diff
/usr/bin/diff3
/usr/bin/sdiff

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*

%files locales -f diffutils.lang
%defattr(-,root,root,-)

